export const LEAD_STAGE = {
  PENDING_LEAD: "PENDING_LEAD",
  COMPLETE_REGISTRATION: "COMPLETE_REGISTRATION",

  ADD_EMPLOYMENT: "ADD_EMPLOYMENT",
  PENDING_EMPLOYEMENT: "PENDING_EMPLOYEMENT_WITH_SELF_EMPLOYEED",

  SEND_EMAIL_OTP: "SEND_EMAIL_OTP", // not helpful
  VRIFY_EMAIL_OTP: "VRIFY_EMAIL_OTP",

  BRE_APPROVED: "BRE_APPROVED",
  BRE_REJECT: "BRE_REJECT",

  LOAN_REQUESTED: "LOAN_REQUESTED",

  SEND_AADHAAR_OTP: "SEND_AADHAAR_OTP", //not helpful
  VERIFY_AADHAAR_KYC: "VERIFY_AADHAAR_KYC",
  REJECT_AADHAR_KYC: "REJECT_AADHAR_KYC",

  SANCTION_COMPLETED: "SANCTION_COMPLETED",
  SANCTION_PENDING: "SANCTION_PENDING",

  DISBURSED: "DISBURSED",
  DISBURSAL_FAILED: "DISBURSAL_FAILED",

  APPLY_RELOAN: "APPLY_RELOAN",

  MANUALLY_REJECT: "MANUALLY_REJECT",
  MANUALLY_APPROVE: "MANUALLY_APPROVE",
};

export const leadStageToRouteMap = {
  COMPLETE_REGISTRATION: "/apply/employment-status",
  ADD_EMPLOYEMENT: "/apply/email",
  VRIFY_EMAIL_OTP: "/apply/upload-bank-statement",
  BRE_APPROVED: "/apply/loan-amount",
  LOAN_REQUESTED: "/apply/adhar-card",
  VERIFY_AADHAAR_KYC: "/apply/e-sign",
  PENDING_EMPLOYEMENT_WITH_SELF_EMPLOYEED: "/apply/thank-you",
  BRE_REJECT: "/apply/thank-you",
  REJECT_AADHAR_KYC: "/apply/thank-you",
  SANCTION_COMPLETED: "/apply/congratulations-card",
  SANCTION_PENDING: "/apply/e-sign",
  DISBURSED: "/apply/congratulations-card",
  DISBURSAL_FAILED: "/apply/thank-you",
  MANUALLY_REJECT: "/apply/thank-you",
  MANUALLY_APPROVE: "/apply/loan-amount",
};
